version: '3.3'

services:
  web:
    build: ./service/web
    privileged: true
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    cap_add:
      - SYS_ADMIN
    command: gunicorn --workers=4 --threads=8 --bind 0.0.0.0:5000 app:app
    restart: always
    expose:
      - 5000
  nginx:
    build: ./service/nginx
    ports:
      - 80:80
    depends_on:
      - web
