version: '3.7'

services:
  web:
    build: ./service/web
    privileged: true
    command: gunicorn --workers=4 --threads=8 --bind 0.0.0.0:5000 app:app
    restart: always
    volumes:
      - ./service/web/:/usr/src/app/
    ports:
      - 5000:5000
